spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo-jap-mybatis?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: kyeepass
    tomcat:
      validation-query: "select 1"
      test-on-borrow: true
      validation-interval: 30000
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 80
      jdbc-interceptors: "ResetAbandonedTimer"
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
flyway:
  out-of-order: true
  enabled: true
server:
  port: 8090